CREATE TABLE TSHIRT(
  TSHIRT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(16) NOT NULL,
  SIZE VARCHAR(5) NOT NULL ,
  COLOUR VARCHAR (16) NOT NULL,
  PRICE BIGINT ,
  AVAILABLE BIGINT
  );

